#!/bin/bash

# Путь к вашему скрипту сборки
BUILD_SCRIPT_PATH=././build.sh

# Проверка наличия скрипта сборки
if [ -f "$BUILD_SCRIPT_PATH" ]; then
  # Запуск скрипта сборки
  bash "$BUILD_SCRIPT_PATH"

  # Автоматический коммит собранных файлов
  git add .
  git commit -m "Auto-commit: Build files for quiz"
else
  echo "Build script not found. Please set the correct path."
fi