name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Make build.sh executable
      run: chmod +x ././build.sh

    - name: Build Quiz App
      run: ././build.sh
      working-directory: ././  

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker Image
      run: docker tag my-nginx:latest ${{ secrets.DOCKER_USERNAME }}/my-nginx:latest
      working-directory: ././  
      
    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-nginx:latest
      working-directory: ././

    - name: Deploy to server
      id: deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      with:
        flags: '-avzr --delete'
        options: ''
        ssh_options: ''
        src: 'public/'
        dest: 'root@85.143.172.183:/var/www/html'

    - name: Display status from deploy
      run: echo "${{ steps.deploy.outputs.status }}"
