name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: my-quiz-app
      uses: actions/my-quiz-app

    - name: Build and run Docker container
      run: |
        docker-compose build
        docker-compose up -d
        docker-compose ps
      working-directory: C:\Soft\PyCharm\my-quiz-app

    - name: Stop Docker container
      run: docker-compose down
      working-directory: C:\Soft\PyCharm\my-quiz-app